fixing bugs but still have errors
I first faced some errors due to missing ?]?, ?;?, and incorrect script of the condition for the remainder to 4 that I?ve solved. Further, the execution of seq2tfrec_kmer.py give the following errors:

AttributeError: module 'tensorflow' has no attribute 'logging'
Which was solved by changing tf.logging to tf.compat.v1.logging

Next error was that python_io was unrecognized which was solved by replacing it with io. 

The last error I?m getting is as follows that I have no clue yet how to solve it:

WARNING: Logging before flag parsing goes to stderr.
? seq2tfrec_kmer.py:224] Processing training/eval set
? seq2tfrec_kmer.py:111] Parsing vocabulary
Traceback (most recent call last):
  File "?/DeepMicrobes/scripts/seq2tfrec_kmer.py", line 238, in <module>
    main()
  File "?/DeepMicrobes/scripts/seq2tfrec_kmer.py", line 225, in main
    training_set_convert2tfrecord(input_seq, output_tfrec, kmer, vocab, seq_type)
  File "?/DeepMicrobes/scripts/seq2tfrec_kmer.py", line 116, in training_set_convert2tfrecord
    seq, label_id = training_set_read_parser(rec)
  File "?/DeepMicrobes/scripts/seq2tfrec_kmer.py", line 53, in training_set_read_parser
    label_id = int(identifier.split('|')[1])
IndexError: list index out of range
Finished.